# Generated by Django 3.0.8 on 2020-07-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, default='', max_length=50)),
                ('LastName', models.CharField(blank=True, default='', max_length=50)),
                ('Password', models.CharField(blank=True, default='', max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('SecurityQuestion', models.CharField(blank=True, default='', max_length=50)),
                ('SecurityAnswer', models.CharField(blank=True, default='', max_length=50)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
            ],
        ),
    ]
