# Generated by Django 3.0.8 on 2020-07-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='SecurityAnswer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='register',
            name='SecurityQuestion',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
